name: Terraform CI/CD

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    name: 'Terraform Plan and Apply'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: 'Login to Azure using Managed Identity'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}  # Managed Identity Client ID
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}  # Azure Tenant ID
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Azure Subscription ID

      - name: 'Initialize Terraform'
        run: | 
          cd modules/resource_group && terraform init 

      - name: 'Terraform Format Check'
        run: terraform fmt -check

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan

